{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo1.py:10: AssertionError"}, "description": "this test fails", "start": 1588912713805, "stop": 1588912713806, "uuid": "689a81c2-9001-44f6-a0b8-572b47dc38db", "historyId": "9e8d23832460ad3c87806390b91ae72c", "testCaseId": "d3ba699b3e70ee73490c0d009b152181", "fullName": "test_alluredemo1#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "PC-20201204TOIX"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}